var someStr;
var myNum;
var myBool;
var age;
var strArr;
myNum = 5;
someStr = "Welcome to Typescript";
myBool = true;
age = 77;
strArr = ["Een", "Josh"];
console.log(someStr, myNum, myBool, age, strArr);
