var someStr;
var myNum;
var myBool;
var age;
var strArr;
var numsArr;
var tupsArr;
myNum = 5;
someStr = "Welcome to Typescript";
myBool = true;
age = 77;
strArr = ["Een", "Josh"];
numsArr = [1, 2, 3, 4];
tupsArr = ["Eben", 29, true];
var myVoid = null;
var myNull = undefined;
var myUndefined = null;
console.log(myNum);
