var someStr;
var myNum;
var myBool;
var age;
var strArr;
var numsArr;
var tupsArr;
myNum = 5;
someStr = "Welcome to Typescript";
myBool = true;
age = 77;
strArr = ["Een", "Josh"];
numsArr = [1, 2, 3, 4];
tupsArr = ["Eben", 29, true];
console.log(someStr, myNum, myBool, age, strArr, numsArr, tupsArr);
